version: "3.4"
services:
  rasa-production:
    image: "bsctemu/presto-vickybot:1.0.3"
  rasa-worker:
    image: "bsctemu/presto-vickybot:1.0.3"
    depends_on:
      - rasa-production
  app:
    image: "bsctemu/presto-vickybot-actions-server:1.0.0"
    expose:
      - "5055"
    depends_on:
      - rasa-production