# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: es

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 3
    # OOV_token: _oov_
  # - name: LanguageModelFeaturizer
  #   # Name of the language model to use
  #   model_name: "roberta"
  #   # Pre-Trained weights to be loaded
  #   model_weights: "PlanTL-GOB-ES/roberta-base-bne"

  #   # An optional path to a specific directory to download and cache the pre-trained model weights.
  #   # The `default` cache_dir is the same as https://huggingface.co/transformers/serialization.html#cache-directory .
  #   cache_dir: null
  # #  Whether to use a shared vocab
  # #   use_shared_vocab: False


### Custom components and classifiers
  - name: sentiment.SentimentEntityExtractor # componente que genera: NEG, NEU, POS
  - name: DIETClassifier # clasificador dual de RASA. 
    epochs: 20
    constrain_similarities: true 
  - name: EntitySynonymMapper # trabaja sobre las entidades y sinónimos

# Fallback and chitchat components
  - name: FallbackClassifier 
    threshold: 0.48 

  - name: ResponseSelector  # necesario para que funcione chitchat
    epochs: 100
    retrieval_intent: chitchat

  - name: ResponseSelector  # necesario para que funcione faq
    epochs: 100
    retrieval_intent: faq

policies: # dialogo
### Transformers dialogue policies:
   - name: TEDPolicy # transformer embedding dialogue
     epochs: 20
     constrain_similarities: true
    #  augmentation_factor: 10 
     
   - name: UnexpecTEDIntentPolicy # el fallback del flujo conversacional
     tolerance: 0.1 # estava a 0.2 i l'he baixat
     epochs: 20

### Conversational contextualization --> se ha alterado esta politica para ver si generamos mayor consistencia en el desarrollo de las conversaciones contextuales
   - name: AugmentedMemoizationPolicy # el tamaño que se tiene en cuenta para el training. se cuentan turnos completos.
     max_history: 8

### Rule policies 
   - name: RulePolicy  # el que regula las rules.yml
     core_fallback_threshold: 0.2
     core_fallback_action_name: "action_default_fallback"
     enable_fallback_prediction: True
     restrict_rules: True
     check_for_contradictions: true

