# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: es

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.


  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true

  # - name: EntitySynonymMapper

  # - name: "SpacyNLP"
  #   model: "es_dep_news_trf"
  #   case_sensitive: False
  # - name: SpacyEntityExtractor

  - name: sentiment.SentimentEntityExtractor
    # other components to extrat entities:
  

  - name: RegexEntityExtractor
    # use lookup tables to extract entities
    use_lookup_tables: True
    # use regexes to extract entities
    use_regexes: True

# other components
  - name: FallbackClassifier
    threshold: 0.5

  - name: ResponseSelector  # Este componente sirve para ajustar el chitchat
    epochs: 100
    retrieval_intent: chitchat
   
# Configuration for Rasa Core. # # See https://rasa.com/docs/rasa/policies for more information.

policies:

   - name: TEDPolicy
     epochs: 100
     constrain_similarities: true
   - name: MemoizationPolicy
     #max_history: 3 #Se ha añadido un ciclo de vida de 3 a los inputs. 
   - name: RulePolicy
   - name: UnexpecTEDIntentPolicy
     max_history: 5
     epochs: 100