# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: es

pipeline:

###basics pre-treatment

  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
### Custom components and classifiers
  - name: sentiment.SentimentEntityExtractor
  - name: DIETClassifier
    epochs: 20
    constrain_similarities: true # revisar 
  - name: EntitySynonymMapper


# Fallback and chitchat components
  - name: FallbackClassifier
    threshold: 0.52

  - name: ResponseSelector  # Este componente sirve para ajustar el chitchat
    epochs: 20
    retrieval_intent: chitchat
   
policies:
### Transformers dialogue policies:
   - name: TEDPolicy
     epochs: 20
     constrain_similarities: true
   - name: UnexpecTEDIntentPolicy
     tolerance: 0.50
     epochs: 20

### Conversational contextualization
   - name: MemoizationPolicy
     max_history: 5  #hiperparámetro que aprende el contexto conversacional. En este caso, seis pasos.

### Rule policies
   - name: RulePolicy #hiperparámetro para manejar cuando pierde contexto conversacional. Si pierde hilo se lanza automat el intent. 
     core_fallback_threshold: 0.3
     core_fallback_action_name: "action_default_fallback"
     enable_fallback_prediction: True

