# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: es

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.

  - name: HFTransformersNLP
    model_weights: "PlanTL-GOB-ES/roberta-base-bne"
    model_name: "roberta"
  - name: LanguageModelTokenizer
  - name: LanguageModelFeaturizer
  # - name: DIETClassifier
  #   epochs: 20


  # - name: "SpacyNLP"
  #   model: "es_dep_news_trf"
  #   case_sensitive: False
  # - name: SpacyEntityExtractor

  - name: sentiment.SentimentEntityExtractor
  - name: DIETClassifier
    epochs: 20
    constrain_similarities: true # revisar 
  - name: EntitySynonymMapper


  # - name: RegexEntityExtractor


  #   # use lookup tables to extract entities
  #   use_lookup_tables: True
  #   # use regexes to extract entities
  #   use_regexes: True

# other components
  - name: FallbackClassifier
    threshold: 0.52

  - name: ResponseSelector  # Este componente sirve para ajustar el chitchat
    epochs: 20
    retrieval_intent: chitchat
   
# Configuration for Rasa Core. # # See https://rasa.com/docs/rasa/policies for more information.

policies:
   - name: TEDPolicy
     epochs: 20
     constrain_similarities: true
   - name: UnexpecTEDIntentPolicy
     tolerance: 0.65
     epochs: 20
   - name: MemoizationPolicy
     max_history: 6  #hiperparámetro que aprende el contexto conversacional. En este caso, seis pasos.
   - name: RulePolicy #hiperparámetro para manejar cuando pierde contexto conversacional. Si pierde hilo se lanza automat el intent. 
     core_fallback_threshold: 0.3
     core_fallback_action_name: "action_default_fallback"
     enable_fallback_prediction: True